# Generated by Codex on 2026-07-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="facultymember",
            name="advising_areas",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="facultymember",
            name="employment_classification",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="facultymember",
            name="faculty_category",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="facultymember",
            name="faculty_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active_full_time", "Active Full-Time"),
                    ("study_leave", "Study Leave"),
                    ("sabbatical_leave", "Sabbatical Leave"),
                ],
                default="active_full_time",
                help_text="Use only when personnel type is Faculty.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="facultymember",
            name="highest_degree",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="facultymember",
            name="og_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="facultymember",
            name="og_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="facultymember",
            name="personnel_type",
            field=models.CharField(
                choices=[
                    ("faculty", "Faculty"),
                    ("academic_staff", "Academic Staff"),
                    ("laboratory_technician", "Laboratory Technician"),
                ],
                default="faculty",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="facultymember",
            name="seo_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="facultymember",
            name="seo_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="facultymember",
            name="specialization_areas",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="facultymember",
            name="position",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
